#!/usr/bin/env bash
# Install V-See so it appears in the desktop application menu (Cinnamon/MATE/etc.)
# like a normal app. Uses your conda env "v-see" and this repo copy.
#
# Usage (from anywhere):
#   /path/to/V-See/packaging/install-linux-launcher.sh
#
# Uninstall:
#   rm -f ~/.local/bin/v-see ~/.local/share/applications/v-see.desktop
#   update-desktop-database ~/.local/share/applications 2>/dev/null || true

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTALL_BIN="${INSTALL_BIN:-$HOME/.local/bin}"
INSTALL_APPS="${INSTALL_APPS:-$HOME/.local/share/applications}"
LAUNCHER="$INSTALL_BIN/v-see"
DESKTOP="$INSTALL_APPS/v-see.desktop"

if ! command -v conda &>/dev/null; then
  echo "Error: conda not on PATH. Initialize Miniconda for this shell, then retry." >&2
  exit 1
fi

CONDA_BASE="$(conda info --base)"
if [[ ! -f "$CONDA_BASE/etc/profile.d/conda.sh" ]]; then
  echo "Error: missing $CONDA_BASE/etc/profile.d/conda.sh" >&2
  exit 1
fi

mkdir -p "$INSTALL_BIN" "$INSTALL_APPS"

# Shell-safe re-use inside the generated launcher (handles spaces in paths).
ROOT_Q="$(printf '%q' "$ROOT")"
CONDA_Q="$(printf '%q' "$CONDA_BASE")"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by packaging/install-linux-launcher.sh — do not edit by hand.
set -euo pipefail
cd $ROOT_Q
source $CONDA_Q/etc/profile.d/conda.sh
conda activate v-see
if [[ -n "\${CONDA_PREFIX:-}" ]]; then
  export LD_LIBRARY_PATH="\${CONDA_PREFIX}/lib\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}"
fi
exec python main.py "\$@"
EOF
chmod +x "$LAUNCHER"

# .desktop Exec: use quoted path if the launcher path contains spaces.
if [[ "$LAUNCHER" == *" "* ]]; then
  DESKTOP_EXEC="Exec=\"$LAUNCHER\""
else
  DESKTOP_EXEC="Exec=$LAUNCHER"
fi
if [[ "$ROOT" == *" "* ]]; then
  DESKTOP_PATH="Path=\"$ROOT\""
else
  DESKTOP_PATH="Path=$ROOT"
fi

cat > "$DESKTOP" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=V-See
Comment=Photo viewer (conda dev install)
$DESKTOP_EXEC
Icon=view-paged
Terminal=false
Categories=Graphics;Viewer;Photography;
$DESKTOP_PATH
EOF

echo "Installed:"
echo "  Launcher:  $LAUNCHER"
echo "  Menu file: $DESKTOP"
echo ""
echo "Log out and back in, or run: update-desktop-database ~/.local/share/applications"
echo "Then open the applications menu and search for V-See."

if command -v update-desktop-database &>/dev/null; then
  update-desktop-database "$INSTALL_APPS" 2>/dev/null || true
fi
